name: chromium
version: 61.0.3163.100
summary: Chromium web browser, open-source version of Chrome
description: |
 An open-source browser project that aims to build a safer, faster, and more
 stable way for all Internet users to experience the web.
confinement: strict

apps:
  chromium:
    command: desktop-launch chromium-browser.launcher
    desktop: usr/share/applications/chromium-browser.desktop
    plugs:
      - browser-sandbox
      - camera
      - cups-control
      - gsettings
      - home
      - mount-observe
      - network
      - network-manager
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - unity7 # required for xdg-open to work
      - upower-observe
      - x11

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

parts:
  ppa-build:
    plugin: nil
    build-packages:
      - software-properties-common
    stage-packages:
      - fonts-noto-cjk
      - fonts-thai-tlwg
      - libgl1-mesa-glx
      - libnss3
      - pulseaudio
    prepare: |
      apt install software-properties-common
      V=61.0.3163.100-0ubuntu0.16.04.1306
      add-apt-repository -y ppa:osomon/chromium-stable
      apt update
      apt install -y chromium-browser=$V chromium-browser-l10n=$V chromium-codecs-ffmpeg-extra=$V
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib
      cp -R /usr/lib/chromium-browser $SNAPCRAFT_PART_INSTALL/usr/lib/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp /usr/bin/chromium-browser $SNAPCRAFT_PART_INSTALL/usr/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc
      cp -R /etc/chromium-browser $SNAPCRAFT_PART_INSTALL/etc/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      cp -R /usr/share/applications/chromium-browser.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      chmod 4555 $SNAPCRAFT_PART_INSTALL/usr/lib/chromium-browser/chrome-sandbox
  launcher:
    plugin: dump
    source: snap
    after: [desktop-gtk3-no-wayland]
    organize:
      chromium-browser.launcher: bin/

  desktop-gtk3-no-wayland:
    # Temporary workaround for https://launchpad.net/bugs/1711393, use a
    # custom branch of the desktop helpers instead of the upstream one.
    source: https://github.com/oSoMoN/snapcraft-desktop-helpers.git
    source-branch: no-wayland
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all

  font-clear-sans-ttf:
    # Until snapd can expose the host system's fonts to snaps (see
    # https://forum.snapcraft.io/t/1796), ship the Clear Sans font family from
    # the Solus project (see https://forum.snapcraft.io/t/2278/3).
    source: https://packages.solus-project.com/unstable/f/font-clear-sans-ttf/font-clear-sans-ttf-1.00-3-1-x86_64.eopkg
    source-type: zip
    plugin: nil
    install: tar -C $SNAPCRAFT_PART_INSTALL -x -f install.tar.xz
