name: chromium
version: 65.0.3325.146
summary: Chromium web browser, open-source version of Chrome
description: |
 An open-source browser project that aims to build a safer, faster, and more
 stable way for all Internet users to experience the web.
confinement: strict

apps:
  chromium:
    command: desktop-launch chromium-browser.launcher
    desktop: usr/share/applications/chromium.desktop
    environment:
      DISABLE_WAYLAND: 1
      CHROME_DESKTOP: chromium.desktop
    plugs:
      - browser-sandbox
      - camera
      - cups-control
      - desktop
      - gsettings
      - home
      - mount-observe
      - network
      - network-manager
      - opengl
      - password-manager-service
      - pulseaudio
      - screen-inhibit-control
      - unity7 # required for xdg-open to work
      - upower-observe
      - x11

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

parts:
  ppa-build:
    plugin: nil
    build-packages:
      - software-properties-common
    stage-packages:
      - libgl1-mesa-glx
      - libgnome-keyring0
      - libnss3
      - pulseaudio
    prepare: |
      apt install software-properties-common
      V=65.0.3325.146-0ubuntu0.16.04.1
      add-apt-repository -y ppa:chromium-team/stable
      apt update
      apt install -y chromium-browser=$V chromium-browser-l10n=$V chromium-codecs-ffmpeg-extra=$V
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib
      cp -R /usr/lib/chromium-browser $SNAPCRAFT_PART_INSTALL/usr/lib/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp /usr/bin/chromium-browser $SNAPCRAFT_PART_INSTALL/usr/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc
      cp -R /etc/chromium-browser $SNAPCRAFT_PART_INSTALL/etc/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps
      cp /usr/share/icons/hicolor/scalable/apps/chromium-browser.svg \
          $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps/chromium.svg
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      cp /usr/share/applications/chromium-browser.desktop \
          $SNAPCRAFT_PART_INSTALL/usr/share/applications/chromium.desktop
      sed -i \
          -e "s:^Exec=chromium-browser\(.*\):Exec=chromium\1:g" \
          -e "s:^Icon=chromium-browser$:Icon=/usr/share/icons/hicolor/scalable/apps/chromium.svg:" \
          $SNAPCRAFT_PART_INSTALL/usr/share/applications/chromium.desktop
      chmod 4555 $SNAPCRAFT_PART_INSTALL/usr/lib/chromium-browser/chrome-sandbox
  launcher:
    plugin: dump
    source: snap
    after: [desktop-gtk3-fixed-cache]
    organize:
      chromium-browser.launcher: bin/
  desktop-gtk3-fixed-cache:
    source: https://github.com/oSoMoN/snapcraft-desktop-helpers.git
    source-branch: xdg-cache-home-in-common
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
  shared-mime-info:
    after: [launcher, ppa-build]
    plugin: nil
    source: .
    stage-packages:
      - shared-mime-info
    build-attributes: [no-system-libraries]
    install: |
      set -eux
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
